spring:
  cache:
    type: redis
    redis:
      time-to-live: PT10S
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:63792}
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/offers
      auto-index-creation: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

scheduling:
  enabled: true

offer:
  http:
    client:
      config:
        connectionTimeout: 1000
        port: 5057
        readTimeout: 1000
        uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com

http:
  offers:
    scheduler:
      request:
        delay: PT3H
auth:
  jwt:
    expirationDays: 30
    secret: ${JWT_SECRET}
    issuer: job-offers-backend

logging:
  level:
    root=INFO: